[FEAT]: Add `Wallet Connect`  connector
ryze-land/ryze-ethereum pull request #6
Opened 2023-08-28 14:37 UTC by matheus-pissaia

2023-08-28 15:31 UTC, matheus-pissaia commented on src/classes/WalletConnectors/WalletConnector.ts
> +    public abstract setChain(chainId: ChainId, provider?: BrowserProvider | WalletConnectProvider): Promise<void>
Does it make sense to add the `WalletConnectProvider` type since im using the provider that was assigned inside the connector?

2023-08-28 15:39 UTC, RauppRafael requested changes

2023-08-28 15:39 UTC, RauppRafael commented on package.json
> +        "ethers": "^6.4.2",
ethers is a peer dependency now

2023-08-28 15:39 UTC, RauppRafael commented on src/classes/WalletConnectors/WalletConnect.ts
> +export class WalletConnect extends WalletConnector {
WalletConnectConnector

2023-08-28 15:39 UTC, RauppRafael commented on src/classes/WalletConnectors/WalletConnect.ts
> +        catch { }
empty catch isnt ideal

2023-08-28 15:39 UTC, RauppRafael commented on src/classes/WalletConnectors/WalletConnector.ts
> +    public abstract setChain(chainId: ChainId, provider?: BrowserProvider | WalletConnectProvider): Promise<void>
yep, makes sense, you really don't need it

2023-08-29 08:36 UTC, RauppRafael requested changes

2023-08-29 08:36 UTC, RauppRafael commented on src/classes/WalletConnectors/WalletConnect.ts
> +export class WalletConnectConnector extends WalletConnector {
filename is different from class name

2023-08-29 08:36 UTC, RauppRafael commented on src/classes/WalletConnectors/WalletConnect.ts
> +            parseInt(chain.split(':')[1] || ''))
```
const chainIds = namespaces.eip155?.chains
    ?.map(chain => parseInt(chain.split(':')[1] || ''))
```

2023-08-29 08:36 UTC, RauppRafael commented on src/classes/WalletConnectors/WalletConnect.ts
> +    chains: number[]
should be typed as ChainId[]

2023-08-29 13:19 UTC, merged